source :rubygems

gem 'rake'
gem 'mocha', '0.11.4'
gem 'rspec', '2.10.0'
gem 'rspec-core', '2.10.1'
gem 'rspec-expectations', '2.10.0'
gem 'rspec-mocks', '2.10.1'
gem 'rspec-puppet', '0.1.3'
gem 'puppetlabs_spec_helper'
gem 'ci_reporter'
gem 'cucumber'
